# We'll use the '3.x spec since it supports the 'cache_from'
# option:
version: '3.7'

services:
  authegy:
    image: icalia-labs.registry-beta.semaphoreci.com/icalialabs/authegy-gem:testing-${GIT_COMMIT_SHORT_SHA:-latest}
    build:
      target: testing
      context: .
      cache_from:
        # Since docker-compose will try to build the unused (at this time) runtime
        # stage, and this project's dev stages and runtime stages start from
        # different images, we need to include the releaseable image here as well
        # - this may change with Docker 19.x:
        - icalia-labs.registry-beta.semaphoreci.com/icalialabs/authegy-gem:testing-${GIT_SHORT_SHA:-latest}
        - icalia-labs.registry-beta.semaphoreci.com/icalialabs/authegy-gem:testing-${TAG_SAFE_BRANCH}
        - icalia-labs.registry-beta.semaphoreci.com/icalialabs/authegy-gem:testing
    command: bundle exec rake spec
    volumes:
      # Given the Docker image sets $HOME to `/usr/src`...
      - ${HOME}/.gem/credentials:/usr/src/.gem/credentials:ro
