version: '3.7'

networks:
  backend:

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:11-alpine
    labels:
      com.icalialabs.plis.group: data
    ports:
      - ${AUTHEGY_PG_PORT:-5432}:5432
    volumes:
      # Mount the postgres data volume
      - postgres_data:/var/lib/postgresql/data
    networks: [ "backend" ]
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd
